name = "KSDrift"
x_ref = "x_ref.npy"
input_shape = [ 512,]
data_type = "None"
x_ref_preprocessed = true
p_val = 0.05
preprocess_at_init = true
update_x_ref = "None"
correction = "bonferroni"
alternative = "two-sided"
n_features = "None"

[meta]
version = "0.12.1.dev0"
version_warning = false

[preprocess_fn]
src = "@cd.pytorch.preprocess.preprocess_drift"
max_len = 512
batch_size = 32

[preprocess_fn.model]
flavour = "pytorch"
src = "preprocess_fn/model"

[preprocess_fn.embedding]
type = "hidden_state"
layers = [ -1, -2, -3, -4, -5, -6, -7, -8,]
src = "preprocess_fn/embedding"
flavour = "pytorch"

[preprocess_fn.tokenizer]
src = "preprocess_fn/tokenizer"
